create table if not exists api_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  method text,
  url text,
  request_headers jsonb,
  request_body text,
  response_status int,
  response_headers jsonb,
  response_body text,
  duration_ms int,
  client_ip text
);

-- Optional: Enable RLS if you want to restrict access
alter table api_logs enable row level security;

-- Allow read access to authenticated users (dashboard)
create policy "Allow read access for authenticated users" on api_logs
  for select using (auth.role() = 'authenticated');

-- Allow insert access for the service role (Edge Function uses anonymous or service role)
-- If the Edge Function uses the anon key, we need to allow anon insert OR
-- better, the Edge Function should use the Service Role Key env var if possible, 
-- but usually it uses the user's key. 
-- For simplicity in a logging context, allow anon insert if you are protected by other means?
-- Actually, the Edge Function runs on the server. We can use the service_role client inside the function 
-- to bypass RLS, OR we grant insert permissions to anon/service_role.
-- Let's assume we use the default client in Deno which uses the Auth header passed by caller.
-- If the caller is "anon", they need permission.

create policy "Allow insert for everyone" on api_logs
  for insert with check (true);
