[common]
exclude_remarks=(请勿使用该节点|导航页|到期|剩余流量|时间|官网|产品|平台|套餐到期|二手倒卖|重置|剩余|过期|机场|订阅|分享)

[custom]
;xr自用规则

;此规则为clash专用的链式代理规则，可能不适用于其他软件
;此规则为clash专用的链式代理规则，可能不适用于其他软件
;此规则为clash专用的链式代理规则，可能不适用于其他软件

;不要随意改变关键字，否则会导致出错

;去广告：支持
;自动测速：支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：支持
;增强国外GFW：支持
;OPENAI选择：支持

;设置规则标志位

ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🔗 链式代理,https://raw.githubusercontent.com/MisakaFxxk/MisakaF_Subconverter/main/Sub/Emby.list
ruleset=🔗 链式代理,https://raw.githubusercontent.com/MisakaFxxk/MisakaF_Subconverter/main/Sub/EmbyVip.list
ruleset=🔗 链式代理,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=🔗 链式代理,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
ruleset=🔗 链式代理,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=🔗 链式代理,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=🔗 链式代理,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=🔗 链式代理,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetEaseMusic.list
ruleset=🔗 链式代理,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
ruleset=🔗 链式代理,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list
ruleset=🔗 链式代理,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
ruleset=🔗 链式代理,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list
ruleset=🔗 链式代理,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=🔗 链式代理,https://raw.githubusercontent.com/jhxxr/script/master/rule/list/bard.list
ruleset=🔗 链式代理,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
ruleset=🔗 链式代理,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=🔗 链式代理,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/DisneyPlus.list
ruleset=🔗 链式代理,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list
ruleset=🔗 链式代理,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=🔗 链式代理,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Spotify.list
ruleset=🔗 链式代理,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🔗 链式代理,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/jhxxr/script/master/rule/list/direct.list
ruleset=🎯 全球直连,[]GEOIP,CN,no-resolve
;ruleset=🎯 全球直连,[]GEOIP,LAN
ruleset=🐟 漏网之鱼,[]FINAL
;设置规则标志位

;设置分组标志位

custom_proxy_group=🔗 链式代理`relay`[]🔭 入口选择`[]✈️ 自建落地
custom_proxy_group=✈️ 自建落地`select`(我的|自建|落地)
custom_proxy_group=🔭 入口选择`select`[]🔮 负载均衡`[]🚀 手动切换`[]🔯 故障转移`[]♻️ 自动选择
custom_proxy_group=♻️ 自动选择`url-test`(^(?!.*(落地|自建|我的)).*)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🔯 故障转移`fallback`(^(?!.*(落地|自建|我的)).*)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🔮 负载均衡`load-balance`(^(?!.*(落地|自建|我的)).*)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🚀 手动切换`select`(^(?!.*(落地|自建|我的)).*)
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🔗 链式代理`[]♻️ 自动选择
;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true

;clash_rule_base=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GeneralClashConfig.yml

;luck