create table if not exists api_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  method text,
  url text,
  request_headers jsonb,
  request_body text,
  response_status int,
  response_headers jsonb,
  response_body text,
  duration_ms int,
  client_ip text
);

alter table api_logs enable row level security;

create policy "Allow read access for authenticated users" on api_logs
  for select using (auth.role() = 'authenticated');

create policy "Allow insert for everyone" on api_logs
  for insert with check (true);
